pipeline {

agent any 

stages {
stage ('git checkout') {
steps {
git branch: 'main' , url: 'https://github.com/Gousia20/my-project-amazon.git'
}
}

stage ('build') {
steps {

sh 'mvn clean package'
}
}

stage ('deploy') {
steps {
        sh 'docker cp target/mywar.war tomcat:/usr/local/tomcat/webapps/'
}
}
}
}















































































